name: Deadline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  getCommentOnIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Get Comment
        uses: actions/github-script@v3
        with:
          script: |
            const issueNumber = context.payload.number
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            })
            const comment = issue.data.body
            console.log(comment)
            core.setOutput('comment', comment)

  checkComment:
    runs-on: ubuntu-latest
    needs: getCommentOnIssue
    steps:
      - name: Check Comment
        id: check
        run: |
          comment=${{ needs.getCommentOnIssue.outputs.comment }}
          if [[ $comment == *"due date"* ]]; then
            echo "::set-output name=hasDueDate::true"
          else
            echo "::set-output name=hasDueDate::false"
          fi # check if comment has due date

  addComment:
    runs-on: ubuntu-latest
    needs: checkComment
    if: ${{ needs.checkComment.outputs.hasDueDate == 'false' }}
    steps:
      - name: Add Comment
        uses: actions/github-script@v3
        with:
          script: |
            const issueNumber = context.payload.issue.number
            const comment = "Please add a due date to this issue."
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: comment
            })

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
