name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  getCommentOnIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Get Comment
        uses: actions/github-script@v3
        with:
          script: |
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 18
            })
            const comment = issue.data.body
            console.log(comment)
            core.setOutput('comment', comment)

  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    steps:
      - uses: kin/gh-action-get-linked-issues@v1.0
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"
      # OPTIONAL: Use the output from the `check-linked-issues` step
      - name: Get the output
        run: ${{ toJSON(steps.check-linked-issues) }}
